### PR TITLE
Patch 1

### PR DESCRIPTION
**Pull request by Codencode**
Field "id_lang" in emailsubscription table
Issue: https://github.com/PrestaShop/PrestaShop/issues/13453

### CODE REVIEW

**Comment by marionf** [comment]
Thank you @Codencode 

Is it possible to display the language in the module below ?

capture d'écran_1494

This could be usefull to avoid going into databse to get this information

**Comment by Codencode** [comment]
> 
> 
> Thank you @Codencode
> 
> Is it possible to add a column to display the language in the module below ?
> 
> capture d'écran_1494
> 
> This could be usefull to avoid going into databse to get this information



> 
> 
> Thank you @Codencode
> 
> Is it possible to add a column to display the language in the module below ?
> 
> capture d'écran_1494
> 
> This could be usefull to avoid going into databse to get this information


@marionf 
I just added the code to do it.

**Comment by marionf** [comment]
@Codencode 

I have the error below when I try to configure the module

capture d'écran_1495

**Comment by Codencode** [comment]
> 
> 
> @Codencode
> 
> I have the error below when I try to configure the module
> 
> capture d'écran_1495

@marionf 
Sorry I made a copy/paste error.
Anyway I solved it.

**Comment by Codencode** [comment]
@marionf 
Previously I also proposed a solution to an error, if you want you can take a look here:
https://github.com/PrestaShop/PrestaShop/pull/13668


Thanks!

**Comment by marionf** [comment]
@Codencode 

I just found a new issue after subscribing to the newsletter with GB language

capture d'écran_1497

> Previously I also proposed a solution to an error, if you want you can take a look here:
PrestaShop/PrestaShop#13668

Your PR should be reviewed by our developers before to be tested

**Comment by Codencode** [comment]
@marionf 

I also did some tests with the GB language and I haven't found problems. However, the error should not depend on the changes I have made.
I believe that the system did not correctly evaluate the "newsletter_date_add" field when registering for the newsletter.

**Comment by marionf** [comment]
Humm, that's weird because I don't have it when I switch on master branch

https://drive.google.com/file/d/15px51utBqqBFaXnhX2BkP0v9VPO3OPd7/view?usp=sharing

**Comment by Codencode** [comment]
Could you send me a copy of your database?

**Comment by Codencode** [comment]
@marionf
I solved it.

Moreover, I noticed that when the user is registring at the site and simultaneously he is registring to the newsletter, if the newsletter voucher is active (configuration NW_VOUCHER_CODE) the system does not send the email with the code. Can I make the change in this patch, or do I need to make a new pull request?

**Comment by Codencode** [comment]
> 
> 
> Humm, that's weird because I don't have it when I switch on master branch
> Please, take a look at the screenrecord below
> 
> https://drive.google.com/file/d/15px51utBqqBFaXnhX2BkP0v9VPO3OPd7/view?usp=sharing

@marionf
I solved it.

Moreover, I noticed that when the user is registring at the site and simultaneously he is registring to the newsletter, if the newsletter voucher is active (configuration NW_VOUCHER_CODE) the system does not send the email with the code. Can I make the change in this patch, or do I need to make a new pull request?
Registration
Configuration

**Comment by marionf** [comment]
@Codencode 

It seems there is still an issue with GB language.
I try to register to the newsletter with GB language and the subscriber isn't displayed in the module

https://drive.google.com/file/d/1zeCY4sXOO7fsf_j6jUWQwk2f-z1fLIVu/view?usp=sharing

> Moreover, I noticed that when the user is registring at the site and simultaneously he is registring to the newsletter, if the newsletter voucher is active (configuration NW_VOUCHER_CODE) the system does not send the email with the code. Can I make the change in this patch, or do I need to make a new pull request?

Could you please create another PR as it's another issue ?

**Comment by Codencode** [comment]
@marionf 
> It seems there is still an issue with GB language.
> I try to register to the newsletter with GB language and the subscriber isn't displayed in the module

The list shows only the active emails. To view the last one, you need to activate the registration via the email sent to you.

> Could you please create another PR as it's another issue?

Yes, can I use version 2.3.3 for the new PR?

**Comment by marionf** [comment]
Oh yes, my bad I forget that !
It seems good for me, thank you @Codencode 
Let's ask for code review now @PrestaShop/prestashop-core-developers 
And sorry but I don't have the answer for the version, let's ask also to @PrestaShop/prestashop-core-developers

**Comment by Codencode** [comment]
> 
> 
> Oh yes, my bad I forget that !
> It seems good for me, thank you @Codencode
> Let's ask for code review now @PrestaShop/prestashop-core-developers
> And sorry but I don't have the answer for the version, let's ask also to @PrestaShop/prestashop-core-developers

@marionf 
Ok,
I asked it because this new modification requires the module to be hooked to 2 hooks, so I have to create instructions for upgrading from the previous version.

Thanks!

**Comment by jolelievre** [comment]
Hello @Codencode 

I'm wondering why do you need to store the language of the user? As you can get it through the customer table, and it is more up to date.
Or do you only need it for visitors that subscribed to the newsletter without creating an account yet?

Also since this is a new feature the new version number should rather be `2.4.0` (the last digit is used for bug fixes)

**Comment by Codencode** [comment]
> 
> 
> Hello @Codencode
> 
> I'm wondering why do you need to store the language of the user? As you can get it through the customer table, and it is more up to date.
> Or do you only need it for visitors that subscribed to the newsletter without creating an account yet?

It is useful to know the language of visitors registered for the newsletter and not to the site.

> Also since this is a new feature the new version number should rather be `2.4.0` (the last digit is used for bug fixes)

It's true, I hadn't really thought of it.

Thank you!

**Comment by jolelievre** [comment]
Also you need to target the `dev` branch the `master` branch is only used by the PrestaShop team when we will release the new module version

**Comment by Codencode** [comment]
> 
> 
> Oh my bad you still need to update the config.xml file for the version as well

Yes, I just did it.

**Comment by Codencode** [comment]
> 
> 
> Also you need to target the `dev` branch the `master` branch is only used by the PrestaShop team when we will release the new module version

Ok. Could you explain me how can I do it?

**Comment by jolelievre** [comment]
You just need to"edit" your PR and change the target branch (I did for you 😉)

**Comment by Codencode** [comment]
> You just need to"edit" your PR and change the target branch (I did for you 😉)

OK, thanks!

**Comment by sarahdib** [comment]
Hello @Codencode 

Thank you for your contribution :)

**Comment by PierreRambaud** [comment]
Thanks @Codencode

**Pull request merged**
